[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "32f5de93e1e0244e10a2576b5ed0835bed5836a5"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "df92e48970c42985b73baef996d4f2ffdcbe886bd3c58950602486553b462784"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.0+0/object_store_ffi.v0.8.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "f029e441a39504b784bfdfcf9c67b9f374230391"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "10ad5a4162790211817485203715d3d5556906cdc7b7e74241cbff635d89de79"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.0+0/object_store_ffi.v0.8.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "5c366a99f5faa3a9ec8504f08aa0dfe4bed110b9"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "4acddb025dbbcb19182ad3b0725ef5a22b21c21d492a73aaf25a47b25e8015f9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.0+0/object_store_ffi.v0.8.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "b7a754ec274aa9cb01ed5f544cf4f532f2c2242d"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "28a1fd4d1b20693c37118c787aa01c9198d4ba38ce281469b9ccd714b881eba3"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.0+0/object_store_ffi.v0.8.0.x86_64-linux-gnu.tar.gz"
