[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "051d40008547ebb6eed02689abb6b5617ba6a389"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "3d5bb034cd886b7d1712fb344c62ae20bbb98640b537e7d59afe823e093afda3"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.1+0/object_store_ffi.v0.10.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "0a3663d5195bee96755c6a5049c13ad8a2f68974"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "e26ad15f6f71fc04918ceb5ee67f4395a8f90943017f798505a9660be5048950"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.1+0/object_store_ffi.v0.10.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "ae71955a8426605a28cf7f46484165cb4da2cc99"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "efd04ffe852d548078cd9361f7455e1c1e8684b68fe26c562122f3741283cad4"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.1+0/object_store_ffi.v0.10.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "8d8ea936c1e687b15d0435b0d16681c59cc6927e"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "6fe013ecdf3979102818dc8bc104ea552df7e377102f94e36899eb0c5b9a12ac"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.1+0/object_store_ffi.v0.10.1.x86_64-linux-gnu.tar.gz"
