[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "368a8bd7e0808c7af14a0df4110db2e8fa0812d7"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "fb7940df96b4b308c9f523ec701e0b7ea442d7a88162fbf7f95b7d3eb14e2ee0"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.0+0/object_store_ffi.v0.10.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "4eb5aea29341c7cb7b8e3d1a17b533f8a443c723"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "c2b0cbf87279aeb5a0b77ebdf2678454d5442a1250636c3650b3bdda6f3b8d0c"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.0+0/object_store_ffi.v0.10.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "29bde4a2b78a648bb02d8983aadaf0d98a5b819e"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "415b82d29e7c0cf4582ca3a745b7decad6a42ae962913f93acfc47c149dbd7d9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.0+0/object_store_ffi.v0.10.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "47c603ba9d5fc6076f7fc28f52bcf0dbb7b62cc3"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "3b4556ed5e9347927b46c07128aa5bdeb2dac3f2056795e5ad4041f4cb341111"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.10.0+0/object_store_ffi.v0.10.0.x86_64-linux-gnu.tar.gz"
