[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "b512da96bf85e3b0ca179adc416a40a4f6b34385"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "c9c0ac163fdc5bfb08b700f510ef1fd89aff5ad290dcf6f1e3c0245796b58fdf"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.1+0/object_store_ffi.v0.11.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "92c5ed8c91b2600c38353791f8a940503fe0a5da"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "094169de93fa6b84cf304115917281d923b69157c8028b9e1af423f92bbf8acc"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.1+0/object_store_ffi.v0.11.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "3e9f2967eca1f6de3ea54fcd86d9f6c3d270ac62"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "f5b81e9ae3fe6056894b92af64a24529d986db3425bbce46c434d01d9d2437e6"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.1+0/object_store_ffi.v0.11.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "b5f99e98f04cc8dd66e79d1fcb802b7492d856be"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "497372ac117216b66586335e4f51f5e377093c87a8b18246b151bc7c0802e0f3"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.1+0/object_store_ffi.v0.11.1.x86_64-linux-gnu.tar.gz"
