[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "1473a87a50f8a24ab0754a1a1af809846e1ec151"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "2a6eedbe484f3ecb7175d9d957baf94263e75c5b6948cb1d03bcba0ef6f90d68"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.0+0/object_store_ffi.v0.11.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "32d23ddc77b8fb8a94d0d6b15c135f827e633b53"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "ccfb75481284bd32df35d9258725337a142b859b1d90ac8e6bea36efe3da5b1a"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.0+0/object_store_ffi.v0.11.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "3c6e2ccbbce6486690c80ed847457e4bbdb5902d"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "fd4e643d45f633e8588895654d2da373cb3565624d1f6569cc23e8ea0a19fe1c"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.0+0/object_store_ffi.v0.11.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "d39f84f6cef0380daef1a58651d75968f0310616"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "2bd510b62f002abd0f0f9fd9ae57287f63dbc1ae0c3158e5f34c6fa9340fb214"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.11.0+0/object_store_ffi.v0.11.0.x86_64-linux-gnu.tar.gz"
