[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "9e0998a5b66f81ac8548c198610b8b17642b168b"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "c276e8b5b007c693cbabe5d874d20c03674803ff972746e3aa85051b73ddf1e5"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.2+0/object_store_ffi.v0.6.2.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "b770a5938cc6093cf6f433cb0e7624c562183dee"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "b3fa0ae05f03fc694fffa120e04977565caf358831cc53f59d3b36e0ac912ea6"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.2+0/object_store_ffi.v0.6.2.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "cb65f2966f0ca5c4c5664748508a9237ce942b1d"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "ae6d4506d6e9f4532d6c2479215d9e09678254bd57e1996074fbf2a0bcb3ddf4"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.2+0/object_store_ffi.v0.6.2.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "bc57dea72d4a7a2aed0b40f453fee1624746f12b"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "5868a65307bdcebce79caccea1dd5af6ee594aa20622ea704c71c19c85e04dc2"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.2+0/object_store_ffi.v0.6.2.x86_64-linux-gnu.tar.gz"
