[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "c10296b8d24d9d2a8199a5897bbb27581110db0a"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "bf10c7596eec4523b42ae88fabdabdad086deab898944ff03ed230a6d087b8f7"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.1+0/object_store_ffi.v0.5.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "9c9d6fb6a2b5c5162065ebe3c75d62e628bd6917"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "4fbd5eaa7e11926dbafad2096cddcd614bb4f621fc0475de75ccda744b7d51f5"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.1+0/object_store_ffi.v0.5.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "276470ea68e23224ff44e770dbba865795d74897"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "42cb1443e3f4552d678c1ff75107a86f13f39bc33dc52005e9b56e4bf3e0e9f6"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.1+0/object_store_ffi.v0.5.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "89fca92db87e1fa626fbc5d043fd8fb991a1f5fe"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "14dcb9efc0275df9211720b7a5d7df66a51c0b5b09368fbe24ce17794267b80c"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.1+0/object_store_ffi.v0.5.1.x86_64-linux-gnu.tar.gz"
