[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "d79b055c51c0ecacb9146d764962eb712518f7c6"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "ac29fa2d21df8eac6031fa8eaa3e2cd5e381f4857745348d0bf9356b2e521d0a"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.5+0/object_store_ffi.v0.12.5.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "169d6803272edef7efb67064b2b969b3d9938b15"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "6bdfc09935185209ed1e85f4ff40984973d425cb511173d02cf4fb98bec55dea"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.5+0/object_store_ffi.v0.12.5.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "2df0842a8d707c2f5b5216beabbfbf0303e82f41"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "bb5c6b073d77e808001cd6e402c100b69d68b7053f4603cb4ae90884a9f137a1"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.5+0/object_store_ffi.v0.12.5.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "99ee58cfcaa5c9b88cfdd25076c640669ca7f312"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "c1434098b60826a54f238ff6cfbda1a0ae6e1bcff5ccca80a85f179a65bac9d0"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.5+0/object_store_ffi.v0.12.5.x86_64-linux-gnu.tar.gz"
