[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "c82c184c39b524841fe939be25b0ef22d57c9eed"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "aa160f3d666fc99db2eedb161b2b77063e18530465460967f57d74131a32a2ea"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.0+0/object_store_ffi.v0.6.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "3adcef6e9511180dc235608358fd2b163e389747"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "11830e3f0af0bccd219865ca09ecfebf51909f34cc69df414d038a4a65130e27"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.0+0/object_store_ffi.v0.6.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "c62a6ff8018ed0e206add9716918d118a2e17bf4"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "345e8f032aece1abc36b5b08034b98b1842882464f745bc9b699c485ca9f33c9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.0+0/object_store_ffi.v0.6.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "46a62b32ea357aa055dcd9b28f6073a5fa412f22"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "71b619fa3de5f53619a13027d8715a831ddb50e92061e3d32e0fc13cb19deb69"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.0+0/object_store_ffi.v0.6.0.x86_64-linux-gnu.tar.gz"
