[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "6e74f8bf9a3da737db1831b0a560070f84185079"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "79bfad0529b595d30ff6aa1bd499f793db4dad6dad4c217cb00a0e15ac516368"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.4.1+0/object_store_ffi.v0.4.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "e05bf70f23abede7e862e41d5edca8369074aa40"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "d89245224afaea2c6c2f6fff1df302abc9080005107d076fa3111b77ae5c66c1"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.4.1+0/object_store_ffi.v0.4.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "f3f56ccecbdfca460fa08578029a55740af392fb"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "65cb5667b2f70df3ceceebf17b28aae96981fa7f730b6575a02c0b4e0c878105"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.4.1+0/object_store_ffi.v0.4.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "3c28f23662c4e817c53007530e304d6e427b2f57"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "0d16fed8a946eb2190f651a9a44ebeec9f878ffe5f0c7d2ca4ed6c7ff29e08ac"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.4.1+0/object_store_ffi.v0.4.1.x86_64-linux-gnu.tar.gz"
