[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "6d1c870e8ef90be463ad77d6b9530d9443304c31"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "1f937fd7a2bdd8c890a765f6526164e9240050b23a46af7f2d8d9960838f0015"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.7.0+0/object_store_ffi.v0.7.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "1f8cff06aa07103ec4a1857a97751f82d62fe34b"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "a7b9469fc598dcfb365d14d296e44d8b2d1dccbfdccae80fef7eeebd86d4130d"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.7.0+0/object_store_ffi.v0.7.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "1b27d41a9b67d1e7eb177c5a2b0c1c0a3c97c164"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "98d7e3ec0b4be2c501410d8473c8ef9420d4281d2175ed4c75f8fe3928903f52"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.7.0+0/object_store_ffi.v0.7.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "7e5cfd84e14b126190006c38b1b424ab7fb64f6e"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "6adcaf838eeaa00f001e48a2707bd084ea38815b5f11bb3ce35c5e8b89b58337"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.7.0+0/object_store_ffi.v0.7.0.x86_64-linux-gnu.tar.gz"
