[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "1524eadfdc84c4f93670ff287d1873641730d163"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "f30cb534f0488ee8892678530b7a72d09ce5d8211ea9556b61300f47e70c74c6"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.4+0/object_store_ffi.v0.6.4.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "72ba8c7af185dedc653665763142284a227c9ffc"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "4e776c25be5d42194aef8a597723b67b471ae0d3e9f23dff009b9c9c3e35a329"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.4+0/object_store_ffi.v0.6.4.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "daee67e91c1e5073ceb17744646db07cac5f387c"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "9a0d23709d396ec166b4b3071efc5476dc74404a280b248193414deccca4898a"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.4+0/object_store_ffi.v0.6.4.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "c2eb1e07d22bf0c6d4b5c72dd034f12b9ae05b30"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "66fd4d8da1ea7ec1f150bf7a27b32aa12369b81cc311388943397d46a8efc8a9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.4+0/object_store_ffi.v0.6.4.x86_64-linux-gnu.tar.gz"
