[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "6aa22743a146e666706e9ba9307337078754d348"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "ed9adff6ccd80c7dd3ffa56a32f5cbb95cbb0a9ec25c78c692198b06d7d3f740"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.1+0/object_store_ffi.v0.12.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "7a219dff3a02dbbc0473ee8c0fafc5e23cbe9a49"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "74a313b0cb51f76773b9c40b0c89ef710896be4b82099ee87d1bacdaf84e0320"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.1+0/object_store_ffi.v0.12.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "747527e7c6a38d9397a1ec195a2cca530bbee428"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "87c47eab795c1d4ba5b6c27d7eaed8d2f7e57dbfdeac433321fa8d3467708e2c"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.1+0/object_store_ffi.v0.12.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "621f4da4480f7c511d2e9984da9a45450436b3a9"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "22bef072517fabaf9824bc2940d3cf10abd4f160693b9c7390f7449b0a2adcdd"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.1+0/object_store_ffi.v0.12.1.x86_64-linux-gnu.tar.gz"
