[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "0537ace5664bf0303700a666746ad55a4b98ad83"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "0bb88b0873b4cb12658dd59be1c6b04ac932081ea6efe147b72583d3409b6c09"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.3+0/object_store_ffi.v0.12.3.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "7effd0b54c4eec04f37ad0c36152abf0d3c620eb"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "d1f1c5f20e9d4c28ce0d699665ffc89c12e17d486133bb479eeb4e74adb706ca"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.3+0/object_store_ffi.v0.12.3.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "0c1bf1d533c001a3dba49cb8b0063d177c0c48d0"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "cfcfaf737ff8eeadf30e4eb7d68e917d824686ca34836e4632f9591c0f3220ba"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.3+0/object_store_ffi.v0.12.3.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "1bdfbbe8422e01360d2658ac0dbb95f7b33eb8f8"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "520d13323e96a917dac6e906f3eea0874267a54e0d227656422b678019cf2741"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.3+0/object_store_ffi.v0.12.3.x86_64-linux-gnu.tar.gz"
