[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "26391d747cd69ddb13f0c00b805d1bf3fa972fa3"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "1530f57d15dd0dfda56c758884a221f23e0289d8b480c78813c900422c573712"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.1+0/object_store_ffi.v0.8.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "7fdf8f55f9624fa1cc58f64bbe21d62c817844ad"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "d067a179166c7c497e44d4848db8ce4c17b75e26729cc157c29fa90c01f48867"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.1+0/object_store_ffi.v0.8.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "d9166697d2c26f5b529e7516fffa8e727cc4022a"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "6c3bbcb1ea569bffba7829417ef589b81bbecf96b30852704a0364d07c02a27f"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.1+0/object_store_ffi.v0.8.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "41a9e6433dc097b1afcd0be7dcac9a0aeb6cc5c5"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "247567175f245fea221a3753173aee22becc24c5a4858d1d7f762160991cf52a"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.8.1+0/object_store_ffi.v0.8.1.x86_64-linux-gnu.tar.gz"
