[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "d3c407f2a24affe2de1c7768f54a65bfe017fb06"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "eb5dad7045317f5c4030b3f4d106e9cfb2d2c05b45c7b45c80a9c66700584b8d"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.2+0/object_store_ffi.v0.12.2.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "757bbab4b8bdf8e9313b609bd02e1097fc1c9370"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "02dc9078c779cb229664a6b567d7d5c9052c18673a45db61c2249d268c988b04"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.2+0/object_store_ffi.v0.12.2.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "2d544f5cca0e5000a2cfcb743c9e58c70731c9a1"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "f154aeaf3cbd50b854047f72763c39308acff190f984c37be4081b3406a6ed0f"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.2+0/object_store_ffi.v0.12.2.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "14ea3ae209549ddcfb98ae570a0fd2cbc40a3505"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "be1aff37624c1f5dd7ea798754dc13813b5de020c5337ff2e547b75ccfbcd82a"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.2+0/object_store_ffi.v0.12.2.x86_64-linux-gnu.tar.gz"
