[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "bddafaa882e2dc6a9156c2536b2d54ee285a42fe"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "7bc4d46bfdc47aca178680c51e8b678eed2481f473ade4b9d9943a90a2b27154"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.0+0/object_store_ffi.v0.5.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "9dc77645f2a662c34ca39466781f302aefebb58a"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "e557cb559c5f7e082a3bdf5de9745bb810bb8d28abe4f4a37708eab2a2801bc9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.0+0/object_store_ffi.v0.5.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "101ac1ebedb77ddffddecce391cd3081e518683d"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "5396d555084c7c10581f6e0cf257387d3897b36657725d9caed08ede9e03fa0b"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.0+0/object_store_ffi.v0.5.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "c40e72824b0820e87564255f77067646ddc2db99"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "5b8478b3953b2739e1c068575768dbf085001a1a913c6792279f9e09152fc721"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.5.0+0/object_store_ffi.v0.5.0.x86_64-linux-gnu.tar.gz"
