[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "1725948adc7c71d48c37f1acd00a6f44d167c750"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "5412a1db1b01cef5670999a7eeebfa09ef66ef1b085a29324d3287b1e5e83a93"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.3+0/object_store_ffi.v0.6.3.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "1ba5698a81529da0d7c489c186340c9c6e73e0b2"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "5b810bc40f48d00ac33b3aadad73da10f4f35c74d2c7034e250826353df725b8"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.3+0/object_store_ffi.v0.6.3.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "682047db967fe73d31a8ccd6648f3b2802db802f"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "b2b0de5706c99ceb73d2ffea137c882a5a68b700ad2538017971573af8b639cd"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.3+0/object_store_ffi.v0.6.3.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "d38c11e296d49a85c74ef21627bf5ff81061a723"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "3180b9964ee5d052a1f46ae7d4507e1268a510d62d1f52ff7688fec23f54b3bf"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.3+0/object_store_ffi.v0.6.3.x86_64-linux-gnu.tar.gz"
