[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "282335150fd7cd9e7505ec9058add3f45292a7b1"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "bd018035b15aadcdec8cc1c86ed000818d57dd2dee6dabd5cfde823e5a13e5b9"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.1+0/object_store_ffi.v0.9.1.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "5d4d8fad7384d3e09b927c44e75e309d668569ce"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "1e3b52a5d856bb6369a3dcf8e53b7f8e7838d9e87fc295dacf2a1ffa401e6420"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.1+0/object_store_ffi.v0.9.1.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "922e7c8dd865dee9952f1d9897eba11b5c85919f"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "4754eae68c68f520533e1d8f09392c0446eb153c0323a946efa1f398b1e67d49"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.1+0/object_store_ffi.v0.9.1.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "2c13ffb4dfe087924913018acff2a076323fd013"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "c57124fe6b6d79bef1f6cb4afab1f19e90a09722e018024e006c7b7503e9eaa2"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.1+0/object_store_ffi.v0.9.1.x86_64-linux-gnu.tar.gz"
