[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "e6568beb1efbaf9abb266910d82dc810aeb7f337"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "01ba82d78998d51ab8226dc078ccd2184045bba66e80f80a0f4c82e130028fb5"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.0+0/object_store_ffi.v0.12.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "274e51825a37866363f9d05e9280f4597ebeadb1"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "72d70a8f6c3ddcf7712240fcb8e07f21c971e3c436756f063b2dd47534a5dc4c"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.0+0/object_store_ffi.v0.12.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "6bd61fa4195cdcb2faa0bf1e9bbf52a90e047d28"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "06cfd28ce054c7c522d3eb6cb96b5bc21dd5445ca083fdf0d819a5826896a794"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.0+0/object_store_ffi.v0.12.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "1ea2b97ccf40d94a4936094df0529d01b89980ed"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "1141601ed9bb4f1c7cae60a1a788ba3c6e6e8a000924efc7ea25a6eebac2f4d3"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.12.0+0/object_store_ffi.v0.12.0.x86_64-linux-gnu.tar.gz"
