[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "640c103174cbd1dcab97783f9a2a66a77dc37f7e"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "2f6bfc0c8c97412ec352d03dff66d46707b371f1ce15ce049865d71d86bda223"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.1.0+0/object_store_ffi.v0.1.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "231687919872a8ec66ceed48d8c4fa498cc9d803"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "209c1c3af0191a9e4616e6ccbb0502d7ca5daada2cc01dae3a41fc75f070d9c2"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.1.0+0/object_store_ffi.v0.1.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "682d2aec29d042ea5ebe9d5da34aba78193e233c"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "1db932d625a1427f1c4765e54f4f794a8917661aebfe37e84dbaf2dc4c12bf9e"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.1.0+0/object_store_ffi.v0.1.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "f8ea6ecb8bd826fa31053a858af9166b783147fb"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "87db091e3fbbb883bdd57ac5bc8f245ee8083ddde8965255cce34f48862f56e8"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.1.0+0/object_store_ffi.v0.1.0.x86_64-linux-gnu.tar.gz"
