[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "be64a9f19c6c7f7f0b26909b620c0671f65d0399"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "f6efa29dfe4451474578900c845fe22b61624c85897d536ed88f206ea16d6950"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.5+0/object_store_ffi.v0.6.5.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "de7e25f0124ccd7bcde399af423314e2173ecd9d"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "7c879777ed6af2fa4d4aded7de265a241e54930cca803e420ce5cda39dccc262"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.5+0/object_store_ffi.v0.6.5.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "39a76bc635cb1f11eaf03ca191785afdb5f6f96f"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "f1c4a3b733cbc9097c20d2b986b1bc6260cb59c039e9523170c2acbe46bfbdc6"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.5+0/object_store_ffi.v0.6.5.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "b1e612d20fe61b8795f7688bf655fa14f8362848"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "f6fde47aacf31e5749f157e3333fa5d85f7b2e4de708619af9b61e329e09b3c3"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.6.5+0/object_store_ffi.v0.6.5.x86_64-linux-gnu.tar.gz"
