[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "6498f1d2fabbe0578975a6d334bd1d1dcd4481ff"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "eee6f6c5367c0c811781a1494d6b97b7cdd8450f346290e7ba08493b5b594167"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.0+0/object_store_ffi.v0.9.0.aarch64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "aarch64"
git-tree-sha1 = "75ec9a0c33851008f6cb34bb2042f6ea0f1745b6"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "ade75b44839486fc56aa0bdc058a4b3df8d9c59c8d5b58c5897ddc31c104f59b"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.0+0/object_store_ffi.v0.9.0.aarch64-linux-gnu.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "e89a5d9fa8038b81825cc005975d75f41549f537"
os = "macos"

    [[object_store_ffi.download]]
    sha256 = "5c370c0b780d1e0aa907cdcd4249790e563d949447999878b46867cd775b470d"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.0+0/object_store_ffi.v0.9.0.x86_64-apple-darwin.tar.gz"
[[object_store_ffi]]
arch = "x86_64"
git-tree-sha1 = "015a5213d69ccd942e6cad1b7bf854b696544214"
libc = "glibc"
os = "linux"

    [[object_store_ffi.download]]
    sha256 = "2ca35e494da0ebcd6ccb21298658d52ed5bcb5b63764c7888836b5b8d260990f"
    url = "https://github.com/JuliaBinaryWrappers/object_store_ffi_jll.jl/releases/download/object_store_ffi-v0.9.0+0/object_store_ffi.v0.9.0.x86_64-linux-gnu.tar.gz"
